dotnet add ProductPriceTracker.Api reference ProductPriceTracker.Core
dotnet add ProductPriceTracker.Api reference ProductPriceTracker.Infrastructure
dotnet add ProductPriceTracker.Infrastructure reference ProductPriceTracker.Core
dotnet add ProductPriceTracker.Worker reference ProductPriceTracker.Core
dotnet add ProductPriceTracker.Worker reference ProductPriceTracker.Infrastructure